# Device IP address
ip_address: 192.168.0.1

# Device password
password: WhatEverYourPasswordIs

# All following parameters are optional.
exporter:
  do_not_remove_this_line:

  # port on which this exporter exposes metrics (default: 5642)
  #port: 5642

  # host on which this exporter listens (default: localhost)
  #host: localhost

